/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package colobot.editor;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JButton;

/**
 *
 * @author Tomek
 */
public class TemplateButton extends JButton {

    private BufferedImage image = null;
    
    /**
     * Creates new form TemplateButton
     */
    public TemplateButton()
    {
        initComponents();
    }
    
    public BufferedImage getImage()
    {
        return image;
    }
    
    public void setImage(BufferedImage image)
    {
        this.image = image;
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        if(image == null) return;
        
        g.drawImage(image, 4, 4, getWidth() - 4, getHeight() - 4,
                0, 0, image.getWidth(), image.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(128, 128));
        setMinimumSize(new java.awt.Dimension(48, 48));
        setPreferredSize(new java.awt.Dimension(72, 72));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
